# Site settings
title: Nanosmasher
email: noreply@domain.com
description: Lots of stuff
author: Nanosmasher

# Internet settings
#twitter_username: nanosmasher
github_username: nanosmasher
#disqus_shortname: jekyll-bootstrap-blog
#gacode: UA-XXXXX-X

# Build settings
encoding: utf-8

highlight: true
markdown: kramdown
highlighter: pygments
excerpt_separator: "<!-- more -->"
kramdown:
  input: GFM

# Navigation settings
baseurl: ""
url: http://nanosmasher.github.io

permalink: '/:categories/:title/'
relative_permalinks: false
paginate_path: '/:categories/page:num/'
paginate: 10

subblogs:
  Cardfight Vanguard: 'cfvg'
  Fighting Games: 'fight'
  Enslave your Internet: 'blog'
  Meta-Blog: 'blog'

include: ['_image','cfvg']

cfvg_navigation:
- text: Home
  url: /cfvg/
  icon: "glyphicon glyphicon-home"
- text: About
  url: /cfvg/about/


  